fix : 경로 오류
경로 오류 수정

신인철 | 25.09.28

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,11 +84,11 @@ jobs:
             # 6.5 application.yml 덮어쓰기 방지
             - name: Do not overwrite application.yml
               run: |
-                  if [ -f /srv/riskview/backend/src/main/resources/application.yml ]; then
-                    echo "✅ application.yml already exists, skipping copy."
+                  if [ -f /home/devuser/actions-runner/_work/RiskView/RiskView/backend/src/main/resources/application.yml ]; then
+                      echo "✅ application.yml already exists, skipping copy."
                   else
-                    echo "⚠️ application.yml is missing! Please place it manually."
-                    exit 1
+                      echo "⚠️ application.yml is missing! Please place it manually."
+                      exit 1
                   fi
 
             # 7. (SELF-HOSTED) 서버 배포 스크립트 '로컬' 실행
